// This file will be auto-generated by Prisma
// For now, we'll create manual types based on your schema

export type Client = {
  id: string;
  firstname: string;
  lastname: string;
  address?: string;
  phone?: string;
  email: string;
  password: string;
  role: ClientRole;
  createdAt: Date;
};

export type Product = {
  id: string;
  name: string;
  description?: string;
  price: number;
  dashboardId: string;
  categoryId: string;
  createdAt: Date;
  updatedAt: Date;
  category: Category;
  dashboard: Dashboard;
};

export type Category = {
  id: string;
  name: string;
  description?: string;
  products: Product[];
};

export type Dashboard = {
  id: string;
  name: string;
  description?: string;
  packId: string;
  products: Product[];
  pages: Page[];
  createdAt: Date;
  updatedAt: Date;
};

export enum ClientRole {
  NORMALCLIENT = 'NORMALCLIENT',
  ADMINISTRATORCLIENT = 'ADMINISTRATORCLIENT'
}

// API Response types
export interface ApiResponse<T> {
  success: boolean;
  data?: T;
  message?: string;
  error?: string;
  pagination?: {
    total: number;
    page: number;
    limit: number;
    totalPages: number;
  };
}